### ISSUE TITLE
v2048.vercel.app — no demo

### ISSUE THREAD

**Issue by Veraellyunjie** [spytheman/v2048#2]
visible:
> V 2048 demo
Authors: @spaceface777, @spytheman and other V contributors
Original game by @gabrielecirulli
Click on the canvas to go into fullscreen mode

That's all.
The canvas is indistinguishable, yet clicking under the text, fullscreen black color occurs without anything.

as seen in firefox 78.11.0esr (64-bit)

**Comment by spytheman** [comment]
The version in this repo, looks like this:
![image](https://user-images.githubusercontent.com/26967/183849441-0873b661-279d-43df-96af-7d65c5cc5516.png)

The version on the https://v2048.vercel.app/ site, is based on the official vlang repository https://github.com/vlang/v/blob/master/examples/2048/2048.v, and looks like this:
![image](https://user-images.githubusercontent.com/26967/183849782-81d62e11-c25e-4593-bbd8-60417a0ce8cc.png)

(Firefox 103.0 in Ubuntu 20.04)
